!!evm.Config
ballots:
- candidateList:
  - {name: Jim Bob, party: Labour}
  name: Test
  numCandidates: 1
  numVotesNeeded: 1
  printMsg: Lower house ballot complete, ballot printing...
- candidateList:
  - {name: Steve Jim, party: CCP}
  - {name: Jimbo, party: Libs}
  name: Yeet
  numCandidates: 2
  numVotesNeeded: 1
  printMsg: Upper house ballot complete, ballot printing....
extraData: {Ballot1PartyVotesRequired: 1, Ballot0Type: Lower House, Ballot1Type: Upper
    House}
